Repository ss220-space/Baystation12, pull requests merged in 2021-07, with the labels that each got.

#13 Ported hotkey system from paradise
  baystation12.dme
  code/__defines/admin.dm
  code/__defines/colors.dm
  code/__defines/misc.dm
  code/__defines/subsystem-priority.dm
  code/__defines/subsystems.dm
  code/_helpers/unsorted.dm
  code/_onclick/click.dm
  code/_onclick/click_inf.dm
  code/_onclick/cyborg.dm
  code/_onclick/hud/ability_screen_objects.dm
  code/_onclick/rig.dm
  code/controllers/subsystems/input.dm
  code/game/verbs/ooc.dm
  code/modules/client/client_procs.dm
  code/modules/keybindings/bindings_admin.dm
  code/modules/keybindings/bindings_ai.dm
  code/modules/keybindings/bindings_atom.dm
  code/modules/keybindings/bindings_carbon.dm
  code/modules/keybindings/bindings_client.dm
  code/modules/keybindings/bindings_human.dm
  code/modules/keybindings/bindings_living.dm
  code/modules/keybindings/bindings_mob.dm
  code/modules/keybindings/bindings_robot.dm
  code/modules/keybindings/focus.dm
  code/modules/keybindings/readme.dm
  code/modules/keybindings/setup.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/login.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/mob_movement.dm
  code/modules/mob/new_player/login.dm
  code/modules/mob/typing_indicator.dm
  interface/interface.dm
  interface/skin.dmf
Labels: enhancement

#27 Fix: voidsuit and jumpsuit
  code/modules/xenoarcheaology/tools/equipment.dm
  infinity/icons/obj/clothing/species/resomi/obj_suit_resomi.dmi
  maps/sierra/items/clothing/exploration.dm
  maps/torch/items/clothing/solgov-head.dm
  maps/torch/items/clothing/solgov-suit.dm
Labels: Маппинг, Спрайты

#29 Bike honkers change to NT41
  maps/sierra/structures/closets/armory.dm
Labels: Маппинг

#33 Fix: patrol ship fixes, sierra crew fixes
  maps/away_inf/sentinel/sentinel-1.dmm
  maps/away_inf/sentinel/sentinel-2.dmm
  maps/away_inf/sentinel/sentinel_crew.dm
  maps/away_inf/sentinel/sentinel_items.dm
  maps/sierra/job/jobs_command.dm
Labels: enhancement, Маппинг

#42 Вуали/визоры таяр не пропадают при отключении
  infinity/code/modules/clothing/glasses/glasses_xeno_veil.dm
Labels: bug

#46 Изменение количества НТ41 в оружейной со старта раунда
  maps/sierra/structures/closets/armory.dm
Labels: Маппинг
