Repository ss220-space/Baystation12, pull requests merged in 2021-11, with the labels that each got.

#76 feat: random selection of the name of the mercenary shuttle from the list
  maps/antag_spawn/mercenary/mercenary_inf.dm
Labels: Маппинг

#70 add: Спрайт :aiKEK: для ИИ
  baystation12.dme
  infinity/code/modules/mob/living/silicon/ai/icons.dm
  infinity/icons/mob/AI.dmi
Labels: Спрайты

#85 add: Excavation Cycler in Petrov
  maps/sierra/sierra-1.dmm
Labels: Маппинг

#87 fix: ert base, sierra minor changes and khaarmany in character editor
  code/game/antagonist/outsider/ert.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/modules/species/mantid/mantid.dm
  maps/antag_spawn/ert/ert_base_inf.dmm
  maps/antag_spawn/ert/ert_inf.dm
  maps/sierra/sierra-1.dmm
  maps/sierra/sierra-2.dmm
Labels: enhancement, Маппинг

#89 Shield for sierra
  code/__defines/shields.dm
  code/modules/shield_generators/shield_generator.dm
  maps/sierra/areas/sierra1.dm
  maps/sierra/areas/sierra3.dm
  maps/sierra/sierra-1.dmm
  maps/sierra/sierra-2.dmm
  maps/sierra/sierra-3.dmm
Labels: enhancement, Маппинг

#92 Hotkeys enhancement + GC timings tweak
  code/_onclick/click.dm
  code/controllers/subsystems/garbage.dm
  code/controllers/subsystems/input.dm
  code/modules/keybindings/bindings_client.dm
  code/modules/keybindings/bindings_mob.dm
  code/modules/keybindings/setup.dm
  interface/interface.dm
Labels: enhancement

#94 Patrol craft update
  maps/away_inf/sentinel/sentinel-1.dmm
Labels: Маппинг

#95 Fix: diagonal movement no longer breaks ventcrawling
  code/modules/ventcrawl/ventcrawl_atmospherics.dm
Labels: enhancement

#96 Добавлены спрайты onmob для xray carabine
  code/modules/projectiles/guns/energy/laser.dm
  icons/mob/onmob/items/lefthand_guns.dmi
  icons/mob/onmob/items/lefthand_guns_secure.dmi
  icons/mob/onmob/items/righthand_guns.dmi
  icons/mob/onmob/items/righthand_guns_secure.dmi
Labels: Спрайты

#97 Спрайты на резоми от Dmiks
  infinity/icons/mob/species/resomi/onmob_head_resomi.dmi
  infinity/icons/obj/clothing/species/resomi/obj_head_resomi.dmi
Labels: Спрайты
