Repository ss220-space/Baystation12, pull requests merged in 2022-03, with the labels that each got.

#153 Added a new headgear - wig
  code/modules/clothing/head/misc.dm
  icons/mob/onmob/items/lefthand_hats.dmi
  icons/mob/onmob/items/righthand_hats.dmi
  icons/mob/onmob/onmob_head.dmi
  icons/obj/clothing/obj_head.dmi
  maps/sierra/loadout/loadout.dm
Labels: Маппинг, Спрайты

#149 Добавление возможности резоми активировать и носить null suit .
  code/modules/clothing/spacesuits/rig/suits/station.dm
  infinity/icons/mob/species/resomi/onmob_head_resomi.dmi
  infinity/icons/mob/species/resomi/onmob_rig_back_resomi.dmi
  infinity/icons/mob/species/resomi/onmob_suit_resomi.dmi
Labels: Спрайты

#154 fix camera tag at AI Core
  maps/sierra/sierra-3.dmm
Labels: Маппинг

#158 fix: bar's scrubber
  maps/sierra/sierra-2.dmm
Labels: Маппинг

#167 Резоми спрайт берета си
  infinity/icons/mob/species/resomi/onmob_head_resomi.dmi
Labels: Спрайты
