Repository ss220-space/Baystation12, pull requests merged in 2022-02, with the labels that each got.

#131 220 mapfix
  maps/sierra/areas/shuttles.dm
  maps/sierra/sierra-1.dmm
  maps/sierra/sierra-3.dmm
Labels: Маппинг

#126 Даём арсеналу Сьерры новый ПП
  maps/sierra/sierra-3.dmm
  maps/sierra/structures/closets/armory.dm
Labels: Маппинг

#121 Fixed resources amount in R&D
  maps/sierra/sierra-3.dmm
Labels: Маппинг

#138 feat: made brand new centcomm map
  maps/sierra/sierra-4.dmm
Labels: Маппинг

#139 feat: replace tactical and merc armor sprites
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/accessories/armor.dm
  icons/mob/onmob/onmob_head.dmi
  icons/mob/onmob/onmob_modular_armor.dmi
  icons/obj/clothing/obj_head.dmi
  icons/obj/clothing/obj_suit_modular_armor.dmi
  maps/sierra/items/clothing/override.dm
Labels: Маппинг, Спрайты

#137 Фикс голых парамедиков
  maps/sierra/job/outfits.dm
Labels: Маппинг

#136 Фиксинг тактикульной водолазки
  code/modules/clothing/under/syndicate.dm
  icons/mob/onmob/onmob_under.dmi
Labels: Спрайты

#132 AI added to traitor blacklist_jobs
  maps/sierra/sierra_antagonism.dm
Labels: Маппинг

#141 feat: add berets for engineer, senior engineer and atmos tech
  code/modules/clothing/head/jobs.dm
  icons/mob/onmob/onmob_head.dmi
  icons/obj/clothing/obj_head.dmi
  maps/sierra/structures/closets/engineering.dm
Labels: Маппинг, Спрайты

#143 tweak: disable ability to spawn as VOX on Liberia
  maps/away_inf/liberia/liberia_jobs.dm
Labels: Маппинг

#144 Теперь абдукторы телепортирую нормально
  maps/antag_spawn/abductors/abductor_equip.dm
Labels: Маппинг

#148 fix: solsnak sprite
  icons/obj/vending.dmi
Labels: Спрайты
