Repository ss220-space/Baystation12, pull requests merged in 2022-07, with the labels that each got.

#255 REMOVE VOX
  maps/away_inf/liberia/liberia_jobs.dm
Labels: Маппинг

#269 Unathi unifrom fixes
  code/modules/client/preference_setup/loadout/lists/xenowear.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/jobs/security.dm
  icons/mob/onmob/Unathi/uniform.dmi
  icons/mob/species/unathi/generated/onmob_feet_unathi.dmi
  icons/mob/species/unathi/generated/onmob_head_unathi.dmi
  icons/mob/species/unathi/generated/onmob_suit_unathi.dmi
  icons/mob/species/unathi/generated/onmob_under_unathi.dmi
  icons/mob/species/unathi/onmob_head_helmet_unathi.dmi
  icons/obj/clothing/obj_feet.dmi
  icons/obj/clothing/obj_head.dmi
  icons/obj/clothing/obj_suit.dmi
  icons/obj/clothing/obj_under.dmi
  infinity/icons/mob/species/unathi/onmob_head_unathi.dmi
  infinity/icons/mob/species/unathi/onmob_suit_unathi.dmi
  infinity/icons/mob/species/unathi/onmob_under_unathi.dmi
  infinity/icons/obj/clothing/species/erosan/hats.dmi
  infinity/icons/obj/clothing/species/erosan/suits.dmi
  maps/torch/icons/mob/unathi/onmob_head_solgov_unathi.dmi
  maps/torch/icons/mob/unathi/onmob_suit_solgov_unathi.dmi
Labels: Маппинг, Спрайты

#263 Feature: IT HUD
  code/__defines/items_clothing.dm
  code/game/machinery/doors/airlock.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/modular_computers/computers/modular_computer/interaction.dm
  code/modules/modular_computers/computers/subtypes/dev_console.dm
  code/modules/modular_computers/computers/subtypes/dev_pda.dm
  icons/mob/onmob/onmob_eyes.dmi
  icons/obj/clothing/obj_eyes.dmi
  maps/sierra/sierra-3.dmm
Labels: Маппинг, Спрайты

#273 Mental Health remap
  maps/sierra/areas/sierra3.dm
  maps/sierra/sierra-1.dmm
  maps/sierra/sierra-2.dmm
  maps/sierra/sierra-3.dmm
Labels: Маппинг

#276 locker's hotfix
  code/game/objects/random/random.dm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/game/objects/structures/crates_lockers/crates.dm
  config/custom_sprites.txt
  icons/obj/closets/closet.dmi
  icons/obj/closets/crate.dmi
  icons/obj/closets/fridge.dmi
  icons/obj/guncabinet.dmi
  maps/away_inf/mining/mining-asteroid.dmm
  maps/sierra/sierra-1.dmm
  maps/sierra/sierra-2.dmm
  maps/sierra/sierra-3.dmm
  maps/sierra/structures/closets/medical.dm
  maps/sierra/structures/closets/misc.dm
Labels: Маппинг, Спрайты

#279 Fix: more unathi sprites fixes
  code/modules/client/preference_setup/loadout/lists/xenowear.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/jobs/security.dm
  icons/mob/onmob/Unathi/mask.dmi
  icons/mob/onmob/onmob_mask.dmi
  icons/mob/species/unathi/generated/onmob_accessories_unathi.dmi
  icons/mob/species/unathi/generated/onmob_feet_unathi.dmi
  icons/mob/species/unathi/generated/onmob_under_unathi.dmi
  icons/obj/clothing/obj_feet.dmi
  infinity/icons/mob/onmob/onmob_accessories.dmi
  infinity/icons/mob/species/unathi/onmob_suit_unathi.dmi
Labels: Спрайты

#274 Mapfix: Mental Health
  maps/sierra/sierra-3.dmm
Labels: Маппинг

#282 lockers coldfix
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/game/objects/structures/crates_lockers/closets/walllocker.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/crates_lockers/med_crate.dm
  code/modules/mining/abandonedcrates.dm
  icons/obj/closets/closet.dmi
  icons/obj/closets/crate.dmi
  icons/obj/closets/walllocker.dmi
  maps/sierra/sierra-3.dmm
  maps/sierra/structures/closets.dm
Labels: Маппинг, Спрайты

#286 map & icon fixes
  code/game/objects/structures/crates_lockers/crates.dm
  icons/obj/closets/bodybag.dmi
  icons/obj/closets/crate.dmi
  icons/obj/closets/walllocker.dmi
  infinity/icons/obj/bureaucracy.dmi
  maps/sierra/sierra-1.dmm
  maps/sierra/sierra-2.dmm
  maps/sierra/sierra-3.dmm
Labels: Маппинг, Спрайты

#283 Mapfix: Observatory floor tiles
  maps/sierra/sierra-3.dmm
Labels: Маппинг

#287 Unathi uniform rework
  code/modules/client/preference_setup/loadout/lists/xenowear.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  icons/mob/species/unathi/generated/onmob_feet_unathi.dmi
  icons/mob/species/unathi/generated/onmob_hands_unathi.dmi
  icons/mob/species/unathi/generated/onmob_suit_unathi.dmi
  icons/mob/species/unathi/generated/onmob_under_unathi.dmi
  icons/mob/species/unathi/onmob_head_helmet_unathi.dmi
  icons/obj/clothing/obj_under.dmi
  infinity/icons/mob/species/unathi/onmob_head_unathi.dmi
  infinity/icons/mob/species/unathi/onmob_suit_unathi.dmi
Labels: Спрайты

#295 unathi and resomi sprites update
  code/modules/clothing/glasses/glasses.dm
  icons/mob/species/unathi/generated/onmob_accessories_unathi.dmi
  icons/mob/species/unathi/generated/onmob_hands_unathi.dmi
  icons/mob/species/unathi/generated/onmob_suit_unathi.dmi
  icons/mob/species/unathi/generated/onmob_under_unathi.dmi
  infinity/code/modules/client/preference_setup/loadout/lists/resomi.dm
  infinity/code/modules/clothing/glasses/glasses_resomi.dm
  infinity/icons/mob/onmob/onmob_accessories.dmi
  infinity/icons/mob/species/resomi/onmob_eyes_resomi.dmi
Labels: Спрайты

#278 IPC Screens update. Добавление кнопок для смены изображения монитора СПУ
  code/__defines/species.dm
  code/modules/client/preference_setup/loadout/lists/xenowear.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/organs/robolimbs.dm
  code/modules/species/species.dm
  code/modules/species/station/machine.dm
  code/modules/sprite_accessories/_accessory.dm
  code/modules/sprite_accessories/accessory_ipc.dm
  icons/mob/human_races/species/ipc/ipc_head_accessories.dmi
  icons/mob/human_races/species/ipc/monitor_icons.dmi
  infinity/code/modules/mob/living/carbon/human/machine_limb_functions.dm
Labels: Спрайты

#300 Examine Flags Fix
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/species/species.dm
  code/modules/sprite_accessories/accessory_ipc.dm
  icons/mob/human_races/species/ipc/ipc_head_accessories.dmi
Labels: Спрайты
