Repository ss220-space/Baystation12, pull requests merged in 2022-11, with the labels that each got.

#399 Feat: Buildmode Copy & Paste mode
  baystation12.dme
  code/_helpers/unsorted.dm
  code/modules/admin/buildmode/copypaste.dm
  icons/misc/buildmode.dmi
Labels: Спрайты

#402 Fix: Стеклянные ведро и тряпка
  baystation12.dme
  code/datums/outfits/tournament.dm
  code/datums/supplypacks/custodial.dm
  code/game/machinery/kitchen/microwave.dm
  code/game/objects/random/random.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/modules/ascent/ascent_doodads.dm
  code/modules/crafting/crafting_farmbot.dm
  code/modules/crafting/crafting_janibot.dm
  code/modules/detectivework/tools/rag.dm
  code/modules/fabrication/designs/general/designs_general.dm
  code/modules/item_worth/worths_list.dm
  code/modules/mob/living/bot/cleanbot.dm
  code/modules/mob/living/bot/farmbot.dm
  code/modules/mob/living/silicon/robot/flying/module_flying_cultivator.dm
  code/modules/mob/living/silicon/robot/modules/module_clerical.dm
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/misc.dm
  code/modules/surgery/organs_internal.dm
  code/modules/surgery/other.dm
  infinity/code/game/gamemodes/cult/cult_items.dm
  infinity/code/game/gamemodes/cult/runes.dm
  infinity/code/modules/clothing/suits/suits.dm
  maps/sierra/structures/closets/services.dm
Labels: Маппинг

#391 Lero
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  infinity/code/modules/client/preference_setup/loadout/lists/cloaks.dm
  infinity/code/modules/client/preference_setup/loadout/lists/infinity.dm
  infinity/code/modules/clothing/accessories/cloak.dm
  infinity/icons/mob/onmob/onmob_accessories.dmi
  infinity/icons/mob/onmob/onmob_feet.dmi
  infinity/icons/mob/onmob/onmob_head.dmi
  infinity/icons/mob/onmob/onmob_suit.dmi
  infinity/icons/mob/onmob/onmob_under.dmi
  infinity/icons/obj/clothing/obj_accessories.dmi
  infinity/icons/obj/clothing/obj_feet.dmi
  infinity/icons/obj/clothing/obj_head.dmi
  infinity/icons/obj/clothing/obj_suit.dmi
  infinity/icons/obj/clothing/obj_under.dmi
  maps/sierra/loadout/loadout_shoes.dm
Labels: Маппинг, Спрайты

#396 Бафф колонистов
  maps/random_ruins/exoplanet_ruins/playablecolony/playablecolony.dm
  maps/random_ruins/exoplanet_ruins/playablecolony2/playablecolony2.dm
Labels: Маппинг

#387 Photocopier + Fax UI's
  baystation12.dme
  code/__defines/webhooks.dm
  code/_helpers/text.dm
  code/modules/admin/admin.dm
  code/modules/paperwork/faxmachine.dm
  code/modules/paperwork/photocopier.dm
  code/modules/webhooks/webhook_fax2discord.dm
  maps/sierra/sierra-4.dmm
  nano/templates/fax.tmpl
  nano/templates/photocopier.tmpl
Labels: Маппинг

#411 FIX: Photocopier and Fax access
  code/modules/paperwork/faxmachine.dm
  code/modules/paperwork/photocopier.dm
  maps/sierra/sierra-1.dmm
Labels: Маппинг

#414 Mapfix: SRV Verne Bridge Holopad, adminpad for ERT base
  maps/antag_spawn/ert/ert_base_inf.dmm
  maps/away/verne/verne-3.dmm
Labels: Маппинг

#418 unathi tail fix plus tail animation.
  code/modules/species/station/lizard.dm
  code/modules/species/station/lizard_subspecies.dm
  icons/mob/human_races/species/unathi/eyes.dmi
  icons/mob/species/unathi/generated/onmob_eyes_unathi.dmi
  icons/mob/species/unathi/unathi_tail.dmi
Labels: Спрайты

#419 taj fixes and sci veil
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/client/preference_setup/loadout/lists/xenowear.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/onmob/onmob_under.dmi
  infinity/code/modules/clothing/glasses/glasses_xeno_veil.dm
  infinity/icons/mob/onmob/onmob_accessories.dmi
  infinity/icons/mob/onmob/onmob_eyes.dmi
  infinity/icons/obj/clothing/obj_eyes.dmi
Labels: Спрайты
