Repository ss220-space/Baystation12, pull requests merged in 2022-09, with the labels that each got.

#352 more underwear from para
  code/modules/clothing/under/miscellaneous.dm
  infinity/code/modules/client/preference_setup/loadout/lists/infinity.dm
  infinity/icons/mob/onmob/onmob_under.dmi
  infinity/icons/obj/clothing/obj_under.dmi
Labels: Спрайты

#351 SRV Verne Upgrade
  maps/away/verne/verne-1.dmm
  maps/away/verne/verne-2.dmm
  maps/away/verne/verne-3.dmm
  maps/away/verne/verne_shuttles.dm
  maps/sierra/sierra-1.dmm
  maps/sierra/sierra-3.dmm
  maps/sierra/sierra_overmap.dm
Labels: Маппинг

#324 [True] Autofire
  code/_onclick/MouseDrag.dm
  code/modules/client/client_procs.dm
  code/modules/mob/mob_helpers.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/mantid.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/projectiles/guns/energy/vox.dm
  code/modules/projectiles/guns/magnetic/magnetic_railgun.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets.dm
  icons/mob/onmob/items/lefthand_guns.dmi
  icons/mob/onmob/items/righthand_guns.dmi
  icons/obj/guns/laserauto.dmi
  infinity/code/modules/mechs/guns.dm
  infinity/code/modules/projectiles/guns/energy/laser.dm
  infinity/code/modules/projectiles/guns/projectile/automatic.dm
  infinity/code/modules/projectiles/guns/projectile/energy/energy.dm
  infinity/code/modules/projectiles/guns/projectile/vietnam.dm
  infinity/customs/niga2012.dm
Labels: Спрайты, Кастомка

#354 Medbay disposal pipes tweak
  maps/sierra/sierra-3.dmm
Labels: Маппинг

#358 tajaran_lore suits
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/onmob/onmob_feet.dmi
  icons/mob/onmob/onmob_suit.dmi
  icons/mob/onmob/onmob_under.dmi
  icons/obj/clothing/obj_feet.dmi
  icons/obj/clothing/obj_suit.dmi
  icons/obj/clothing/obj_under.dmi
  infinity/code/modules/client/preference_setup/loadout/lists/xenowear.dm
  infinity/code/modules/clothing/shoes/shoes.dm
  infinity/code/modules/clothing/suits/suits_xeno.dm
Labels: Спрайты

#357 Sprite abyss
  code/datums/supplypacks/munitions.dm
  code/game/machinery/_machines_base/stock_parts/legacy_parts.dm
  code/game/machinery/atmoalter/canister.dm
  code/game/machinery/vending.dm
  code/game/objects/munition.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/modules/client/preference_setup/loadout/lists/accessories.dm
  code/modules/client/preference_setup/loadout/lists/tactical.dm
  code/modules/clothing/under/accessories/armor.dm
  code/modules/clothing/under/accessories/badges.dm
  code/modules/overmap/disperser/disperser.dm
  code/modules/overmap/disperser/disperser_charge.dm
  code/modules/power/smes.dm
  code/modules/power/smes_construction.dm
  code/modules/xenoarcheaology/boulder.dm
  code/modules/xenoarcheaology/tools/artifact_analyser.dm
  code/modules/xenoarcheaology/tools/artifact_harvester.dm
  code/modules/xenoarcheaology/tools/suspension_generator.dm
  icons/mob/onmob/onmob_accessories.dmi
  icons/obj/atmos.dmi
  icons/obj/clothing/obj_accessories.dmi
  icons/obj/clothing/ties.dmi
  icons/obj/disperser.dmi
  icons/obj/mining.dmi
  icons/obj/munitions.dmi
  icons/obj/power.dmi
  icons/obj/rollerbed.dmi
  icons/obj/shipping_crates.dmi
  icons/obj/stock_parts.dmi
  icons/obj/xenoarchaeology.dmi
  infinity/code/modules/client/preference_setup/loadout/lists/armor.dm
  infinity/icons/obj/terminals_holo.dmi
Labels: Спрайты

#355 voxship spawn rate buff
  maps/away/voxship/voxship.dm
Labels: Маппинг

#365 SFV Sentinel Upgrade
  maps/away_inf/sentinel/sentinel-1.dmm
  maps/away_inf/sentinel/sentinel_shuttle.dm
  maps/sierra/sierra-1.dmm
  maps/sierra/sierra_overmap.dm
Labels: Маппинг

#364 Киборг для хейста
  maps/antag_spawn/heist/heist_base_inf.dmm
Labels: Маппинг

#343 Little ambience overhaul
  code/game/area/Space Station 13 areas.dm
  maps/away_inf/mining/mining_areas.dm
  maps/sierra/areas/sierra1.dm
  maps/sierra/areas/sierra2.dm
  maps/sierra/areas/sierra3.dm
  maps/sierra/sierra_areas.dm
  maps/torch/torch_areas.dm
  sound/ambience/ai/ai1.ogg
  sound/ambience/ai/ai2.ogg
  sound/ambience/ai/ai3.ogg
  sound/ambience/ai/ambimalf.ogg
  sound/ambience/ai/ambservers.wav
  sound/ambience/ai/ambxerxes_looped.wav
  sound/ambience/chapel/chapel1.ogg
  sound/ambience/chapel/chapel2.ogg
  sound/ambience/chapel/chapel3.ogg
  sound/ambience/chapel/chapel4.ogg
  sound/ambience/engineering/atmospherics1.ogg
  sound/ambience/engineering/engineering1.ogg
  sound/ambience/engineering/engineering2.ogg
  sound/ambience/engineering/engineering3.ogg
  sound/ambience/hangar/hangar1.ogg
  sound/ambience/hangar/hangar2.ogg
  sound/ambience/hangar/hangar3.ogg
  sound/ambience/hangar/hangar4.ogg
  sound/ambience/hangar/hangar5.ogg
  sound/ambience/hangar/hangar6.ogg
  sound/ambience/maintenance/maintenance1.ogg
  sound/ambience/maintenance/maintenance10.ogg
  sound/ambience/maintenance/maintenance11.ogg
  sound/ambience/maintenance/maintenance12.ogg
  sound/ambience/maintenance/maintenance13.ogg
  sound/ambience/maintenance/maintenance14.wav
  sound/ambience/maintenance/maintenance15.ogg
  sound/ambience/maintenance/maintenance2.ogg
  sound/ambience/maintenance/maintenance3.ogg
  sound/ambience/maintenance/maintenance4.ogg
  sound/ambience/maintenance/maintenance5.ogg
  sound/ambience/maintenance/maintenance6.ogg
  sound/ambience/maintenance/maintenance7.ogg
  sound/ambience/maintenance/maintenance8.ogg
  sound/ambience/maintenance/maintenance9.ogg
  sound/ambience/space/aurora_caelus.ogg
  sound/ambience/space/space1.ogg
  sound/ambience/space/space_serithi.ogg
  sound/ambience/substation/substation1.ogg
  sound/ambience/substation/substation2.ogg
  sound/ambience/substation/substation3.ogg
  sound/ambience/substation/substation4.ogg
  sound/ambience/substation/substation5.ogg
  sound/ambience/substation/substation6.ogg
  sound/ambience/substation/substation7.ogg
  sound/ambience/substation/substation8.ogg
Labels: Маппинг

#369 Skrell new hair
  code/modules/sprite_accessories/accessory_skrell.dm
  icons/mob/human_races/species/skrell/hair.dmi
Labels: Спрайты

#367 Spritepack
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/accessories/badges.dm
  code/modules/clothing/under/miscellaneous.dm
  infinity/code/modules/client/preference_setup/loadout/lists/xenowear.dm
  infinity/icons/mob/onmob/onmob_suit.dmi
  infinity/icons/obj/clothing/obj_suit.dmi
Labels: Спрайты

#366 Mapfix: SFV Sentinel Atmospherics
  maps/away_inf/sentinel/sentinel-1.dmm
Labels: Маппинг

#370 Sound fix
  maps/away/derelict/derelict_areas.dm
Labels: Маппинг
