Repository ss220-space/Baystation12, pull requests merged in 2022-12, with the labels that each got.

#420 new atmos tank sprites
  icons/atmos/tank.dmi
Labels: Спрайты

#431 Farfleet first day patchup
  code/datums/trading/weaponry.dm
  maps/away_inf/farfleet/farfleet.dm
  maps/away_inf/farfleet/farfleet_structures.dm
Labels: Маппинг

#394 Paramount pre-reintegration
  code/datums/outfits/wizardry.dm
  code/game/antagonist/outsider/paramount.dm
  code/game/objects/items/weapons/weaponry.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/wiz_robe.dm
  code/modules/projectiles/effects.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/psionics/equipment/cerebro_enhancers.dm
  code/modules/psionics/equipment/psipower_tk.dm
  code/modules/psionics/events/mini_spasm.dm
  code/modules/psionics/faculties/coercion.dm
  code/modules/psionics/faculties/energistics.dm
  code/modules/psionics/faculties/psychokinesis.dm
  icons/effects/projectiles.dmi
  icons/mob/onmob/feet.dmi
  icons/mob/onmob/onmob_feet.dmi
  icons/mob/onmob/onmob_hands.dmi
  icons/mob/onmob/onmob_head.dmi
  icons/mob/onmob/onmob_suit.dmi
  icons/mob/onmob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/obj_feet.dmi
  icons/obj/clothing/obj_hands.dmi
  icons/obj/clothing/obj_head.dmi
  icons/obj/clothing/obj_suit.dmi
  icons/obj/clothing/suits.dmi
  maps/antag_spawn/ninja/ninja_base_inf.dmm
  maps/antag_spawn/wizard/wizard_base_inf.dmm
  sound/misc/foundation_alarm.ogg
  sound/misc/foundation_restore.ogg
Labels: Маппинг, Спрайты

#433 Feat: SFV Sentinel Missile Retrofit
  maps/away_inf/sentinel/sentinel-1.dmm
  maps/away_inf/sentinel/sentinel-2.dmm
  maps/away_inf/sentinel/sentinel_areas.dm
  maps/away_inf/sentinel/sentinel_presets.dm
  maps/away_inf/sentinel/sentinel_turbolift.dm
Labels: Маппинг

#382 Фикс камер и освещения в кафетерии.
  maps/sierra/areas/sierra1.dm
  maps/sierra/sierra-1.dmm
  maps/sierra/sierra-2.dmm
Labels: Маппинг
