Repository ss220-space/Baystation12, pull requests merged in 2022-06, with the labels that each got.

#228 Tint to windoor
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/structures/window.dm
  maps/sierra/sierra-1.dmm
  maps/sierra/sierra-3.dmm
Labels: Маппинг

#233 Tweak: change icon for detective suit
  icons/mob/onmob/onmob_under.dmi
Labels: Спрайты

#238 Twix: fix some critical bug (probably), and tweak some features to ho…
  code/game/objects/items/bouquet.dm
  code/game/objects/random/random.dm
  code/modules/clothing/suits/armor.dm
  infinity/code/game/objects/items/hookah.dm
  infinity/code/game/objects/items/tobacco.dm
  infinity/icons/obj/item/hookah.dmi
  infinity/sound/effects/hookah1.ogg
  infinity/sound/effects/hookah_lit.ogg
Labels: Спрайты

#242 Cargo minor rework
  code/__defines/research.dm
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/autopsy.dm
  code/game/objects/items/weapons/surgery_tools.dm
  code/game/objects/random/random.dm
  code/modules/materials/definitions/materials_metal.dm
  code/modules/materials/definitions/materials_organic.dm
  code/modules/materials/definitions/materials_wood.dm
  code/modules/materials/material_sheets.dm
  code/modules/paperwork/photography.dm
  code/modules/reagents/reagent_containers/glass.dm
  maps/sierra/sierra-1.dmm
  maps/sierra/sierra-3.dmm
  maps/sierra/structures/closets/supply.dm
Labels: Маппинг

#240 new icons for buttons, and more
  code/game/machinery/buttons.dm
  code/game/machinery/computer/guestpass.dm
  code/game/machinery/doors/blast_door.dm
  code/game/machinery/lightswitch.dm
  code/game/objects/structures/window.dm
  icons/obj/buttons.dmi
  icons/obj/computer.dmi
  icons/obj/extinguisher.dmi
  icons/obj/power.dmi
  icons/obj/stationobjs.dmi
  maps/antag_spawn/ninja/ninja_base_inf.dmm
  maps/away_inf/blueriver/blueriver-2.dmm
  maps/away_inf/sentinel/sentinel-1.dmm
  maps/away_inf/sentinel/sentinel-2.dmm
  maps/away_inf/smugglers/smugglers.dmm
  maps/sierra/sierra-1.dmm
  maps/sierra/sierra-3.dmm
Labels: Маппинг, Спрайты

#249 minor map fix [MDB IGNORE]
  maps/away_inf/yacht/yacht.dmm
  maps/sierra/sierra-2.dmm
Labels: Маппинг

#252 job/roboticist skill buff
  maps/sierra/job/jobs_research.dm
Labels: Маппинг

#256 Нововведение: Требование к отыгранному времени в ветках проффессий.
  baystation12.dme
  code/game/jobs/job/job.dm
  code/game/jobs/job/silicon.dm
  code/modules/client/experience.dm
  code/modules/client/preference_setup/occupation/occupation.dm
  maps/sierra/job/jobs_cargo.dm
  maps/sierra/job/jobs_command.dm
  maps/sierra/job/jobs_engineering.dm
  maps/sierra/job/jobs_exploration.dm
  maps/sierra/job/jobs_medical.dm
  maps/sierra/job/jobs_research.dm
  maps/sierra/job/jobs_security.dm
Labels: Маппинг

#260 Maptweak: handrails for GUP, exosuit frame for Verne
  maps/away/verne/verne-2.dmm
  maps/sierra/sierra-1.dmm
Labels: Маппинг

#261 Feature: IT HUD
  code/__defines/items_clothing.dm
  code/game/machinery/doors/airlock.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/modular_computers/computers/modular_computer/interaction.dm
  code/modules/modular_computers/computers/subtypes/dev_console.dm
  code/modules/modular_computers/computers/subtypes/dev_pda.dm
  icons/mob/onmob/onmob_eyes.dmi
  icons/obj/clothing/obj_eyes.dmi
  maps/sierra/sierra-3.dmm
Labels: Маппинг, Спрайты

#262 Tweak: more chance for shield to block if held twohanded
  code/game/objects/items/weapons/shields.dm
  maps/sierra/sierra-3.dmm
Labels: Маппинг
