Repository ss220-space/Baystation12, pull requests merged in 2022-08, with the labels that each got.

#308 Orbiting for ghosts + hud
  baystation12.dme
  code/__defines/subsystem-priority.dm
  code/_helpers/global_access.dm
  code/_helpers/matrices.dm
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/ghost.dm
  code/_onclick/hud/ghost_screen_objects.dm
  code/controllers/subsystems/orbit.dm
  code/datums/orbit.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/turfs/turf.dm
  code/modules/mob/animations.dm
  code/modules/mob/observer/ghost/ghost.dm
  icons/mob/screen_ghost.dmi
Labels: Спрайты

#310 Feat: fixed orbiting for ghosts + hud
  baystation12.dme
  code/__defines/subsystem-priority.dm
  code/_helpers/global_access.dm
  code/_helpers/matrices.dm
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/ghost.dm
  code/_onclick/hud/ghost_screen_objects.dm
  code/controllers/subsystems/orbit.dm
  code/datums/orbit.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/turfs/turf.dm
  code/modules/mob/animations.dm
  code/modules/mob/observer/ghost/ghost.dm
  icons/mob/screen_ghost.dmi
Labels: Спрайты

#294 Bar rework. Part1.
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/storage/misc.dm
  code/game/objects/structures/shotgun_rack.dm
  code/modules/hydroponics/grown.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Ethanol.dm
  icons/obj/storage.dmi
  icons/obj/vending.dmi
  maps/sierra/job/outfits.dm
  maps/sierra/sierra-1.dmm
  maps/sierra/sierra-2.dmm
  maps/sierra/sierra-3.dmm
  maps/sierra/structures/closets/services.dm
Labels: Маппинг, Спрайты

#317 Chat badges
  code/_helpers/lists.dm
  code/_helpers/text.dm
  code/datums/communication/ooc.dm
  icons/chatbadges.dmi
  icons/chattags.dmi
Labels: Спрайты

#320 HOTFIX of "Bar rework part1"
  code/game/objects/items/weapons/storage/misc.dm
  maps/sierra/sierra-1.dmm
  maps/sierra/sierra-2.dmm
Labels: Маппинг

#325 Bar_pipe_and_pizza_fix
  maps/sierra/sierra-2.dmm
Labels: Маппинг

#344 Ивент
  maps/sierra/sierra-1.dmm
  maps/sierra/sierra-2.dmm
  maps/sierra/sierra-3.dmm
  maps/sierra/sierra-4.dmm
  maps/sierra/sierra_setup.dm
Labels: Маппинг

#340 protecting server from double apple razkumar
  code/modules/projectiles/projectile.dm
  infinity/code/game/objects/items/hookah.dm
  maps/sierra/sierra-2.dmm
  maps/sierra/sierra-4.dmm
Labels: Маппинг

#342 Гест пассы офисам капитана и ГП + патроны бармена
  code/game/objects/items/weapons/storage/boxes.dm
  maps/sierra/sierra-2.dmm
  maps/sierra/sierra-3.dmm
  maps/sierra/structures/closets/services.dm
Labels: Маппинг

#345 sprites for loadout
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/onmob/onmob_mask.dmi
  icons/mob/species/unathi/generated/onmob_mask_unathi.dmi
  infinity/code/modules/client/preference_setup/loadout/lists/infinity.dm
  infinity/icons/mob/onmob/onmob_under.dmi
  infinity/icons/obj/clothing/obj_under.dmi
Labels: Спрайты
