Repository ss220-space/Baystation12, pull requests merged in 2023-12, with the labels that each got.

#689 FIX: Xeno sprite sheets for exploration leader HCM
  maps/sierra/items/rigs.dm
  maps/torch/icons/mob/skrell/onmob_head_solgov_skrell.dmi
  maps/torch/icons/mob/tajara/onmob_head_solgov_tajara.dmi
  maps/torch/icons/mob/tajara/onmob_suit_solgov_tajara.dmi
  maps/torch/icons/mob/unathi/onmob_feet_solgov_unathi.dmi
  maps/torch/icons/mob/unathi/onmob_hands_solgov_unathi.dmi
  maps/torch/icons/mob/unathi/onmob_head_solgov_unathi.dmi
  maps/torch/icons/mob/unathi/onmob_suit_solgov_unathi.dmi
Labels: Маппинг, Спрайты

#693 FEAT: EC rank badges for Sierra
  code/controllers/subsystems/jobs.dm
  code/modules/client/preference_setup/loadout/loadout.dm
  maps/sierra/items/clothing/accessory.dm
  maps/sierra/loadout/loadout_accessories.dm
  maps/sierra/sierra.dm
Labels: Маппинг

#685 Massive mech fixes,tweaks and upgrades.
  baystation12.dme
  code/__defines/antagonists.dm
  code/datums/uplink/uplink_items.dm
  code/modules/mechs/equipment/combat.dm
  code/modules/mechs/equipment/utility.dm
  code/modules/mechs/premade/_premade.dm
  code/modules/mechs/premade/heavy.dm
  code/modules/mechs/premade/powerloader.dm
  code/modules/projectiles/guns/energy/laser.dm
  icons/mecha/mech_equipment.dmi
  icons/mecha/mech_weapon_overlays.dmi
  icons/obj/guns/railgun_old_heavy.dmi
  infinity/code/datums/uplink/badassery.dm
  infinity/code/datums/uplink/services.dm
  infinity/code/modules/mechs/armour.dm
  infinity/code/modules/mechs/guns.dm
  infinity/code/modules/mechs/premade/ert.dm
  infinity/code/modules/projectiles/guns/energy/advanced_ion_rifle.dm
  maps/antag_spawn/ert/ert_base_inf.dmm
Labels: Маппинг, Спрайты

#692 RoboRemap
  maps/sierra/sierra-3.dmm
Labels: Маппинг

#694 Resomi insdustrial hardsuit support
  code/modules/clothing/spacesuits/rig/suits/station.dm
  infinity/icons/mob/species/resomi/onmob_feet_resomi.dmi
  infinity/icons/mob/species/resomi/onmob_hands_resomi.dmi
  infinity/icons/mob/species/resomi/onmob_head_resomi.dmi
  infinity/icons/mob/species/resomi/onmob_rig_back_resomi.dmi
  infinity/icons/mob/species/resomi/onmob_suit_resomi.dmi
Labels: Спрайты

#696 Robo remap fix
  maps/sierra/sierra-3.dmm
Labels: Маппинг

#700 Feat: assorted loadout changes
  code/modules/client/preference_setup/loadout/lists/utility.dm
  infinity/code/modules/client/preference_setup/loadout/lists/infinity.dm
  maps/sierra/loadout/loadout_accessories.dm
  maps/torch/items/clothing/solgov-under.dm
Labels: Маппинг
