Repository ss220-space/Baystation12, pull requests merged in 2023-01, with the labels that each got.

#435 Res eye
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/tanks/tank_types.dm
  code/modules/client/preference_setup/loadout/lists/uniforms.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/under/corporate.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/jobs/medsci.dm
  icons/effects/species.dmi
  icons/mob/onmob/onmob_under.dmi
  icons/obj/clothing/obj_under.dmi
  infinity/code/modules/client/preference_setup/loadout/lists/infinity.dm
  infinity/code/modules/client/preference_setup/loadout/lists/resomi.dm
  infinity/code/modules/clothing/glasses/glasses_resomi.dm
  infinity/code/modules/clothing/suits/suits_resomi.dm
  infinity/code/modules/clothing/under/under.dm
  infinity/code/modules/clothing/under/under_resomi.dm
  infinity/icons/mob/onmob/onmob_under.dmi
  infinity/icons/mob/species/resomi/onmob_accessories_resomi.dmi
  infinity/icons/mob/species/resomi/onmob_back_resomi.dmi
  infinity/icons/mob/species/resomi/onmob_belt_resomi.dmi
  infinity/icons/mob/species/resomi/onmob_ears_resomi.dmi
  infinity/icons/mob/species/resomi/onmob_eyes_resomi.dmi
  infinity/icons/mob/species/resomi/onmob_feet_resomi.dmi
  infinity/icons/mob/species/resomi/onmob_hands_resomi.dmi
  infinity/icons/mob/species/resomi/onmob_head_resomi.dmi
  infinity/icons/mob/species/resomi/onmob_suit_resomi.dmi
  infinity/icons/mob/species/resomi/onmob_under_resomi.dmi
  infinity/icons/obj/clothing/obj_under.dmi
  infinity/icons/obj/clothing/species/resomi/obj_accessories_resomi.dmi
  infinity/icons/obj/clothing/species/resomi/obj_eyes_resomi.dmi
  infinity/icons/obj/clothing/species/resomi/obj_suit_resomi.dmi
  infinity/icons/obj/clothing/species/resomi/obj_under_resomi.dmi
  maps/sierra/items/clothing/storages.dm
  maps/sierra/job/outfits.dm
  maps/sierra/loadout/loadout_uniform.dm
  maps/sierra/structures/closets/research.dm
Labels: Маппинг, Спрайты

#441 Rd lab coat
  icons/mob/onmob/onmob_suit.dmi
  icons/obj/clothing/obj_suit.dmi
Labels: Спрайты

#434 Feat: SRV Verne Science Upgrade
  maps/away/verne/verne-1.dmm
  maps/away/verne/verne-2.dmm
  maps/away/verne/verne-3.dmm
  maps/away/verne/verne.dm
  maps/away/verne/verne_jobs.dm
Labels: Маппинг

#437 Paramount Crhonicles: Mobility and Mercenary
  baystation12.dme
  code/datums/outfits/spec_op.dm
  code/datums/uplink/highly_visible_and_dangerous_weapons.dm
  code/game/gamemodes/paramount/paramount.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/psionics/equipment/cerebro_enhancers.dm
  code/modules/psionics/equipment/foundation_weapon.dm
  code/modules/psionics/equipment/psipower_blade.dm
  code/modules/psionics/equipment/psipower_tele.dm
  code/modules/psionics/equipment/psipower_tk.dm
  code/modules/psionics/faculties/energistics.dm
  icons/mob/onmob/items/lefthand.dmi
  icons/mob/onmob/items/righthand.dmi
  icons/mob/onmob/onmob_head.dmi
  icons/obj/clothing/obj_head.dmi
  icons/obj/psychic_powers.dmi
  infinity/code/game/machinery/security_scanner.dm
Labels: Спрайты

#443 Feat: SRV Verne improvements & additional info pages
  code/modules/overmap/ships/ship.dm
  maps/away/verne/verne-1.dmm
  maps/away/verne/verne-2.dmm
  maps/away/verne/verne-3.dmm
  maps/away/verne/verne.dm
  maps/away/verne/verne_shuttles.dm
  maps/away_inf/sentinel/sentinel-1.dmm
  maps/away_inf/sentinel/sentinel-2.dmm
Labels: Маппинг

#444 Farfleet mapfixes
  maps/away_inf/farfleet/farfleet-1.dmm
  maps/away_inf/farfleet/farfleet-2.dmm
Labels: Маппинг

#446 ICCG MBR and MR-735
  code/datums/trading/weaponry.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  icons/mob/onmob/items/lefthand_guns.dmi
  icons/mob/onmob/items/righthand_guns.dmi
  icons/mob/onmob/onmob_back.dmi
  icons/obj/guns/48x32guns.dmi
  icons/obj/guns/mbr.dmi
  icons/obj/guns/mr735.dmi
  maps/away_inf/farfleet/farfleet-2.dmm
Labels: Маппинг, Спрайты

#452 unathi/eyes and res clothes fix
  icons/mob/human_races/species/unathi/eyes.dmi
  infinity/code/modules/client/preference_setup/loadout/lists/resomi.dm
Labels: Спрайты

#450 Hotfix: SRV Verne core console access
  maps/away/verne/verne-2.dmm
  maps/away/verne/verne-3.dmm
Labels: Маппинг

#456 Add: New Year 2023 contest posters
  code/game/objects/effects/decals/contraband.dm
  infinity/code/game/objects/effects/decals/posters.dm
  infinity/icons/obj/posters.dmi
  maps/away_inf/farfleet/farfleet-1.dmm
  maps/sierra/sierra-2.dmm
  maps/sierra/sierra-3.dmm
Labels: Маппинг, Спрайты

#462 Brig Re-armed
  code/datums/supplypacks/security.dm
  code/modules/fabrication/designs/general/designs_arms_ammo.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  infinity/code/game/objects/items/weapons/storage/belt.dm
  maps/sierra/structures/closets/armory.dm
Labels: Маппинг

#466 Feat: Colorful floor light
  code/game/machinery/floor_light.dm
  icons/obj/machines/floor_light.dmi
Labels: Спрайты
