Repository ss220-space/Baystation12, pull requests merged in 2023-02, with the labels that each got.

#470 Hookah
  baystation12.dme
  code/modules/projectiles/projectile.dm
  infinity/code/game/objects/items/hookah.dm
  maps/sierra/sierra-2.dmm
  maps/sierra/sierra-4.dmm
Labels: Маппинг

#488 Fix: icon path for ICCGN
  code/modules/submaps/submap_join.dm
  maps/away_inf/farfleet/farfleet_crew.dm
  maps/away_inf/farfleet/farfleet_items.dm
  packs/faction_iccgn/obj_accessories_iccgn.dmi
  packs/faction_iccgn/onmob_accessories_iccgn.dmi
  packs/faction_iccgn/ranks.dm
Labels: Маппинг, Спрайты

#457 add (sprites) onyxbay haircuts port
  icons/mob/human_races/species/human/hair_infinity.dmi
  infinity/code/modules/sprite_accessories/accessory_hair.dm
Labels: Спрайты

#495 Farfleet and Sentinel fixes
  maps/away/verne/verne-3.dmm
  maps/away_inf/bearcat/bearcat-2.dmm
  maps/away_inf/farfleet/farfleet-1.dmm
  maps/away_inf/farfleet/farfleet-2.dmm
  maps/away_inf/liberia/liberia.dmm
  maps/away_inf/sentinel/sentinel-1.dmm
  maps/away_inf/sentinel/sentinel-2.dmm
  maps/away_inf/yacht/yacht.dmm
  maps/sierra/sierra-1.dmm
  maps/sierra/sierra-2.dmm
Labels: Маппинг

#490 Feat: Fleet and Army branches and ranks, uniform vendor for SFV Sentinel
  code/modules/projectiles/guns/projectile/automatic.dm
  icons/obj/vending.dmi
  infinity/code/modules/sprite_accessories/accessory_hair.dm
  maps/away/verne/verne.dm
  maps/away/verne/verne_shuttles.dm
  maps/away_inf/sentinel/sentinel-1.dmm
  maps/away_inf/sentinel/sentinel-2.dmm
  maps/away_inf/sentinel/sentinel.dm
  maps/away_inf/sentinel/sentinel_crew.dm
  maps/away_inf/sentinel/sentinel_items.dm
  maps/away_inf/sentinel/sentinel_shuttle.dm
  maps/away_inf/sentinel/sentinel_structures.dm
  maps/sierra/sierra_ranks.dm
Labels: Маппинг, Спрайты

#496 РЕМАП МОСТИКА (переремап в связи с конфликом файлов)
  maps/sierra/sierra-2.dmm
  maps/sierra/sierra-3.dmm
  maps/sierra/structures/closets/command.dm
Labels: Маппинг

#493 Skrell accessories icon fix
  code/modules/clothing/clothing.dm
  code/modules/clothing/ears/skrell.dm
  icons/mob/onmob/Skrell/ears.dmi
  icons/mob/onmob/ears.dmi
Labels: Спрайты

#499 Bridgeremap floordecalfix
  maps/sierra/sierra-2.dmm
  maps/sierra/sierra-3.dmm
Labels: Маппинг

#500 Uplink login
  code/datums/uplink/uplink_sources.dm
  code/game/objects/items/devices/uplink.dm
  icons/obj/radio.dmi
  tgui/packages/tgui/index.js
  tgui/packages/tgui/interfaces/UplinkLogin.tsx
  tgui/packages/tgui/styles/interfaces/UplinkLogin.scss
  tgui/packages/tgui/styles/main.scss
  tgui/packages/tgui/styles/themes/blank-dark.scss
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
Labels: Спрайты

#502 Improved OFD for solship
  code/modules/overmap/disperser/disperser_charge.dm
  code/modules/overmap/disperser/disperser_circuit.dm
  code/modules/overmap/disperser/disperser_console.dm
  code/modules/overmap/disperser/disperser_fire.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
  maps/away_inf/sentinel/sentinel-1.dmm
  maps/away_inf/sentinel/sentinel-2.dmm
  maps/away_inf/sentinel/sentinel_areas.dm
  maps/away_inf/sentinel/sentinel_crew.dm
  maps/away_inf/sentinel/sentinel_items.dm
  maps/away_inf/sentinel/sentinel_structures.dm
Labels: Маппинг

#505 Mapfix: Sentinel and Farfleet minor map fixes
  maps/away_inf/farfleet/farfleet-2.dmm
  maps/away_inf/sentinel/sentinel-1.dmm
  maps/away_inf/sentinel/sentinel-2.dmm
  maps/away_inf/sentinel/sentinel_turbolift.dm
Labels: Маппинг

#508 Maptweak: additional navpoints for Mining Station, Sentinel map tweaks
  maps/away/miningstation/miningstation.dm
  maps/away_inf/miningstation/miningstation.dmm
  maps/away_inf/sentinel/sentinel-1.dmm
  maps/away_inf/sentinel/sentinel.dm
  maps/away_inf/sentinel/sentinel_shuttle.dm
  maps/sierra/sierra-1.dmm
Labels: Маппинг

#510 ICCGN Faf Fix
  maps/away_inf/farfleet/farfleet-2.dmm
Labels: Маппинг
