Repository ss220-space/Baystation12, pull requests merged in 2023-11, with the labels that each got.

#658 Mech nuke sprite fix
  icons/mecha/mech_equipment.dmi
  icons/mecha/mech_weapon_overlays.dmi
  infinity/code/modules/mechs/guns.dm
Labels: Спрайты

#660 Updates 9E sprites, moves G40E to ERT standard armory
  code/modules/projectiles/guns/energy/laser.dm
  icons/mob/onmob/items/lefthand_guns.dmi
  icons/mob/onmob/items/righthand_guns.dmi
  icons/mob/onmob/onmob_back.dmi
  icons/mob/onmob/onmob_head.dmi
  icons/obj/clothing/obj_head.dmi
  icons/obj/guns/laser_sniper.dmi
  infinity/code/modules/clothing/under/under.dm
  maps/antag_spawn/ert/ert_base_inf.dmm
  maps/antag_spawn/ert/ert_inf.dm
  maps/away_inf/sentinel/sentinel_crew.dm
  maps/away_inf/sentinel/sentinel_items.dm
  maps/away_inf/sentinel/sentinel_structures.dm
  maps/torch/icons/mob/onmob_accessories_solgov.dmi
  maps/torch/icons/obj/obj_accessories_solgov.dmi
Labels: Маппинг, Спрайты

#657 Colony R&D upgrade
  maps/random_ruins/exoplanet_ruins/playablecolony_inf/colony.dmm
Labels: Маппинг

#653 Fix: add ten glass to the chemistry
  maps/sierra/sierra-3.dmm
Labels: Маппинг

#667 Adds Raider Vessel away-site
  maps/away_inf/raider_vessel/raider_vessel.dm
  maps/away_inf/raider_vessel/raider_vessel.dmm
  maps/away_inf/raider_vessel/raider_vessel_areas.dm
  maps/away_inf/raider_vessel/raider_vessel_sprites.dmi
  maps/sierra/sierra.dm
Labels: Маппинг, Спрайты

#664 New Custom shit in loadout from Leroy
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/under/miscellaneous.dm
  infinity/icons/customs/infinity_custom_items_mob.dmi
  infinity/icons/customs/infinity_custom_items_obj.dmi
  maps/sierra/loadout/loadout_head.dm
  maps/sierra/loadout/loadout_shoes.dm
  maps/sierra/loadout/loadout_suit.dm
  maps/sierra/loadout/loadout_uniform.dm
Labels: Маппинг, Спрайты

#671 Revert "New Custom shit in loadout from Leroy"
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/under/miscellaneous.dm
  infinity/icons/customs/infinity_custom_items_mob.dmi
  infinity/icons/customs/infinity_custom_items_obj.dmi
  maps/sierra/loadout/loadout_head.dm
  maps/sierra/loadout/loadout_shoes.dm
  maps/sierra/loadout/loadout_suit.dm
  maps/sierra/loadout/loadout_uniform.dm
Labels: Маппинг, Спрайты

#668 Adds Spy Station away-site
  infinity/code/modules/clothing/under/under.dm
  maps/away_inf/spy_station/spy_station.dm
  maps/away_inf/spy_station/spy_station.dmm
  maps/away_inf/spy_station/spy_station_areas.dm
  maps/sierra/sierra.dm
Labels: Маппинг

#675 Fixes Spy Station
  maps/away_inf/spy_station/spy_station_sprites.dmi
Labels: Маппинг, Спрайты

#677 Fixes Ascent Caulship whitelists requirements
  maps/away/ascent_caulship/ascent_jobs.dm
Labels: Маппинг

#678 Tweaks 5th Fleet Centcomm
  code/modules/paperwork/faxmachine.dm
  maps/away_inf/sentinel/sentinel_crew.dm
  maps/away_inf/sentinel/sentinel_items.dm
  maps/sierra/sierra-4.dmm
Labels: Маппинг

#679 Hides Spy Station from Navigation data
  maps/away_inf/spy_station/spy_station.dm
Labels: Маппинг

#662 FEAT: Improved passport icons, additional passport loadout options
  infinity/code/game/objects/items/loadout_xeno.dm
  infinity/code/game/objects/items/passport.dm
  infinity/icons/obj/item/passport.dmi
  maps/sierra/items/items.dm
Labels: Маппинг, Спрайты

#672 Xray new sprites
  icons/obj/guns/xray.dmi
  icons/obj/guns/xray_pistol.dmi
Labels: Спрайты

#683 Mech energy shield upgrade
  code/modules/mechs/equipment/combat.dm
  icons/mecha/mech_equipment.dmi
  sound/mecha/mech_shield_down.ogg
  sound/mecha/mech_shield_up.ogg
  sound/mecha/shield_deflector_fail.ogg
Labels: Спрайты
