Repository ss220-space/Baystation12, pull requests merged in 2023-09, with the labels that each got.

#602 Small map fixes, MPC & Vox atmos revamps and more
  code/modules/client/preference_setup/loadout/lists/tactical.dm
  code/modules/clothing/under/accessories/armor.dm
  code/modules/paperwork/faxmachine.dm
  icons/mob/onmob/onmob_mask.dmi
  icons/mob/onmob/onmob_modular_armor.dmi
  icons/obj/clothing/obj_mask.dmi
  icons/obj/clothing/obj_suit_modular_armor.dmi
  maps/antag_spawn/mercenary/mercenary_inf.dm
  maps/away/ascent_caulship/_ascent_caulship.dm
  maps/away/ascent_caulship/ascent_shuttles.dm
  maps/away/verne/verne_shuttles.dm
  maps/away/voxship/voxship-2.dmm
  maps/away_inf/bearcat/bearcat.dm
  maps/away_inf/sentinel/sentinel-1.dmm
  maps/away_inf/sentinel/sentinel-2.dmm
  maps/sierra/sierra-1.dmm
  maps/sierra/sierra-2.dmm
  maps/sierra/sierra-3.dmm
  maps/sierra/sierra-4.dmm
  maps/sierra/sierra.dm
  maps/sierra/sierra_overmap.dm
  maps/sierra/sierra_shuttles.dm
Labels: Маппинг, Спрайты

#546 New counselor sub-professions without psionics
  maps/sierra/job/jobs_medical.dm
Labels: Маппинг

#555 Miniature cooling unit
  code/game/objects/items/devices/suit_cooling.dm
  code/modules/fabrication/designs/general/designs_general.dm
  icons/mob/onmob/onmob_belt.dmi
  icons/obj/suitcooler.dmi
  maps/antag_spawn/mercenary/mercenary_base.dmm
  maps/away/verne/verne-2.dmm
  maps/away_inf/liberia/liberia.dmm
  maps/sierra/sierra-1.dmm
  maps/sierra/sierra-3.dmm
Labels: Маппинг, Спрайты

#587 Сooling organ for IPCs
  baystation12.dme
  code/__defines/mobs.dm
  code/game/machinery/bioprinter.dm
  code/game/objects/structures/external_cooling_device.dm
  code/modules/item_worth/reagents.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/silicon/robot/analyzer.dm
  code/modules/organs/internal/cooling_system.dm
  code/modules/organs/internal/species/fbp.dm
  code/modules/species/station/machine.dm
  icons/obj/iv_drip.dmi
  icons/obj/surgery.dmi
  maps/sierra/sierra-3.dmm
Labels: Маппинг, Спрайты

#607 Fixes Ascent Caulship
  code/modules/ascent/ascent_outfit.dm
  maps/away/ascent_caulship/_ascent_caulship.dm
  maps/away/ascent_caulship/ascent-1.dmm
  maps/away/ascent_caulship/ascent_jobs.dm
Labels: Маппинг

#608 Remaps IAA Office by Chichmuch
  maps/sierra/sierra-3.dmm
Labels: Маппинг

#609 Fixes IAA Office
  maps/sierra/sierra-3.dmm
Labels: Маппинг

#616 Updates Security Alt voidsuit sprite
  code/modules/clothing/spacesuits/void/station.dm
  icons/mob/light_overlays.dmi
  icons/mob/onmob/onmob_head.dmi
  icons/mob/onmob/onmob_suit.dmi
  icons/mob/species/skrell/onmob_head_skrell.dmi
  icons/mob/species/skrell/onmob_suit_skrell.dmi
  icons/mob/species/tajaran/helmet.dmi
  icons/mob/species/tajaran/suit.dmi
  icons/obj/clothing/obj_head.dmi
  icons/obj/clothing/obj_suit.dmi
  icons/obj/clothing/species/skrell/obj_head_skrell.dmi
  icons/obj/clothing/species/skrell/obj_suit_skrell.dmi
  icons/obj/clothing/species/tajaran/hats.dmi
  icons/obj/clothing/species/tajaran/suits.dmi
  icons/obj/light_overlays.dmi
  infinity/icons/mob/species/unathi/onmob_head_unathi.dmi
  infinity/icons/mob/species/unathi/onmob_suit_unathi.dmi
  infinity/icons/obj/clothing/species/erosan/hats.dmi
  infinity/icons/obj/clothing/species/erosan/suits.dmi
Labels: Спрайты

#597 ИПС на патрульном корабле
  maps/away_inf/sentinel/sentinel_crew.dm
Labels: Маппинг

#598 Цветные корпуса для ИПС
  code/modules/sprite_accessories/accessory_ipc.dm
  icons/mob/human_races/cyberlimbs/shellguard/shellguard_main.dmi
  icons/mob/human_races/species/default_markings.dmi
Labels: Спрайты

#617 Manstopper rounds
  code/game/objects/items/weapons/storage/boxes.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/projectile/bullets.dm
  icons/obj/ammo.dmi
  maps/sierra/structures/closets/armory.dm
Labels: Маппинг, Спрайты
