Repository ss220-space/Baystation12, pull requests merged in 2023-10, with the labels that each got.

#627 VoxScrap5
  code/modules/clothing/suits/alien.dm
  icons/mob/species/vox/head.dmi
  icons/mob/species/vox/onmob_head_vox.dmi
  icons/obj/clothing/obj_head.dmi
  maps/away/voxship/voxship-2.dmm
Labels: Маппинг, Спрайты

#629 Updates ERT sprites
  code/modules/clothing/head/helmet.dm
  code/modules/item_worth/worths_list.dm
  icons/mob/onmob/onmob_accessories.dmi
  icons/mob/onmob/onmob_back.dmi
  icons/mob/onmob/onmob_head.dmi
  icons/mob/onmob/onmob_rig_back.dmi
  icons/mob/onmob/onmob_suit.dmi
  icons/mob/species/tajaran/helmet.dmi
  icons/obj/clothing/obj_accessories.dmi
  icons/obj/clothing/obj_head.dmi
  icons/obj/clothing/obj_suit.dmi
  infinity/code/modules/clothing/under/under.dm
  infinity/icons/mob/onmob/onmob_rig_back.dmi
  maps/antag_spawn/ert/ert_base_inf.dmm
  maps/antag_spawn/ert/ert_inf.dm
  maps/sierra/sierra_ranks.dm
Labels: Маппинг, Спрайты

#634 Fix: resolve tests ci errors and warnings
  code/__defines/colors.dm
  code/_helpers/text.dm
  code/controllers/subsystems/garbage.dm
  code/controllers/subsystems/timer.dm
  code/datums/communication/channel.dm
  code/game/antagonist/station/traitor.dm
  code/game/gamemodes/objective.dm
  code/game/machinery/buttons.dm
  code/game/machinery/computer/guestpass.dm
  code/game/machinery/doors/blast_door.dm
  code/game/machinery/hologram.dm
  code/game/machinery/syndicatebeacon.dm
  code/game/machinery/vending.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/items/cryobag.dm
  code/game/objects/items/rescuebag.dm
  code/game/objects/items/weapons/AI_modules.dm
  code/game/objects/structures/crates_lockers/closets/__closet.dm
  code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
  code/game/world.dm
  code/modules/asset_cache/asset_cache.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/client/client_procs.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/suits/alien.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/flufftext/TextFilters.dm
  code/modules/mob/living/simple_animal/hostile/commanded/commanded.dm
  code/modules/mob/living/simple_animal/hostile/commanded/rex.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/say.dm
  code/modules/modular_computers/terminal/terminal_commands.dm
  code/modules/overmap/projectiles/missiles/missile.dm
  code/modules/overmap/projectiles/projectile.dm
  code/modules/overmap/ships/computers/engine_control.dm
  code/modules/overmap/ships/computers/sensors.dm
  code/modules/overmap/ships/panicbutton.dm
  code/modules/paperwork/faxmachine.dm
  code/modules/power/singularity/singularity.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/psionics/equipment/foundation_weapon.dm
  code/modules/reagents/Chemistry-Grinder.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/unit_tests/zas_tests.dm
  icons/mob/custom_items_mob.dmi
  icons/mob/custom_synthetic.dmi
  icons/obj/custom_items_obj.dmi
  icons/obj/gate.dmi
  infinity/code/game/objects/items/tobacco.dm
  infinity/code/modules/sprite_accessories/accessory_hair.dm
  maps/away/verne/verne-2.dmm
  maps/away_inf/ascent/ascent_jobs.dm
  maps/away_inf/sentinel/sentinel.dm
  maps/away_inf/sentinel/sentinel_shuttle.dm
  maps/sierra/sierra.dm
  maps/sierra/sierra_overmap.dm
  test/check-paths.sh
Labels: Маппинг, Спрайты

#636 Fix exosuit circuit rack sprite .dm
  code/modules/mechs/equipment/utility.dm
  icons/mecha/mech_equipment.dmi
Labels: Спрайты

#641 Fixed hair swept back
  icons/mob/human_races/species/human/hair.dmi
Labels: Спрайты

#642 Added stasis bag in med
  maps/sierra/sierra-3.dmm
Labels: Маппинг

#643 Paramedic jackets in med
  maps/sierra/sierra-3.dmm
Labels: Маппинг

#639 Hardsuit storage module
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/clothing/spacesuits/rig/rig_attackby.dm
  code/modules/research/designs/designs_mechfab.dm
  icons/obj/rig_modules.dmi
Labels: Спрайты

#651 Voxship Remap
  maps/away/voxship/voxship-2.dmm
Labels: Маппинг

#655 Биркет Лонгпад
  maps/away/bearcat/bearcat-2.dmm
Labels: Маппинг
