Repository ss220-space/Baystation12, pull requests merged in 2023-03, with the labels that each got.

#491 DF posters
  infinity/code/game/objects/effects/decals/posters.dm
  infinity/icons/obj/posters.dmi
Labels: Спрайты

#511 Feat: Add new Beards
  code/modules/sprite_accessories/_accessory_facial.dm
  icons/mob/human_races/species/human/facial.dmi
Labels: Спрайты

#509 Brig remap
  baystation12.dme
  icons/obj/drinks.dmi
  maps/sierra/sierra-3.dmm
  packs/prison_hydro.dm
Labels: Маппинг, Спрайты

#513 Новая катана для ниндзи
  code/game/objects/items/weapons/material/swords.dm
  code/modules/clothing/under/accessories/holster.dm
  code/modules/clothing/under/accessories/storage.dm
  icons/mob/onmob/items/lefthand.dmi
  icons/mob/onmob/items/righthand.dmi
  icons/obj/clothing/obj_accessories.dmi
  icons/obj/weapons/melee_physical.dmi
  sound/weapons/katana_swipe.ogg
Labels: Спрайты

#517 Brig remap + fixes. No Conflicts?
  baystation12.dme
  code/modules/modular_computers/computers/subtypes/preset_laptop.dm
  icons/obj/drinks.dmi
  maps/sierra/sierra-3.dmm
  packs/prison_hydro.dm
Labels: Маппинг, Спрайты

#519 Mapfix: removed emergency closet from airlock
  maps/sierra/sierra-1.dmm
Labels: Маппинг

#524 Returned and remastered spooky statue to build
  baystation12.dme
  infinity/code/modules/mob/living/simple_animal/hostile/statue.dm
  infinity/icons/mob/statue.dmi
Labels: Спрайты
