Repository ss220-space/Baystation12, pull requests merged in 2024-02, with the labels that each got.

#714 Mech Customization feature upgrade
  code/datums/supplypacks/nonessent.dm
  code/datums/trading/goods.dm
  code/game/objects/items/paintkit.dm
  code/modules/item_worth/worths_list.dm
  code/modules/mechs/mech_interaction.dm
  icons/mecha/mech_decals.dmi
  infinity/customs/elloncake.dm
  infinity/customs/taushai.dm
  maps/random_ruins/exoplanet_ruins/playablecolony_inf/colony.dmm
  maps/sierra/sierra-3.dmm
Labels: Маппинг, Спрайты, Кастомка

#711 Feat: change EMP impact on the exosuit and its energy shield behaviour
  baystation12.dme
  code/modules/mechs/equipment/combat.dm
  code/modules/mechs/mech_damage.dm
  infinity/code/modules/projectiles/guns/energy/advanced_ion_rifle.dm
  maps/antag_spawn/ert/ert_base_inf.dmm
Labels: Маппинг

#721 Меганопки для гостоты
  baystation12.dme
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/ghost.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/observer/following.dm
  code/modules/mob/observer/ghost/ghost.dm
  code/modules/mob/observer/ghost/orbit.dm
  icons/hud/screen_ghost.dmi
  tgui/packages/tgui/interfaces/Orbit.js
Labels: Спрайты

#705 Feat: add IPC exonet organ
  baystation12.dme
  code/__defines/mobs.dm
  code/datums/extensions/interactive.dm
  code/game/machinery/bioprinter.dm
  code/game/objects/topic.dm
  code/modules/modular_computers/computers/modular_computer/core.dm
  code/modules/modular_computers/computers/modular_computer/hardware.dm
  code/modules/modular_computers/computers/modular_computer/interaction.dm
  code/modules/modular_computers/computers/modular_computer/variables.dm
  code/modules/modular_computers/computers/subtypes/dev_exonet_connection_system.dm
  code/modules/modular_computers/hardware/_hardware.dm
  code/modules/modular_computers/hardware/battery_module.dm
  code/modules/modular_computers/hardware/hard_drive.dm
  code/modules/modular_computers/hardware/network_card.dm
  code/modules/modular_computers/hardware/portable_hard_drive.dm
  code/modules/modular_computers/hardware/processor_unit.dm
  code/modules/modular_computers/ntos/ntos.dm
  code/modules/nano/interaction/default.dm
  code/modules/organs/internal/exonet_connection_system.dm
  code/modules/research/designs/designs_modular_computer.dm
  code/modules/species/station/machine.dm
  icons/obj/surgery.dmi
  infinity/code/modules/mob/living/carbon/human/machine_limb_functions.dm
  infinity/code/modules/research/designs/designs_modular_computer.dm
Labels: Спрайты

#720 Feat: add radial menu for toolsets augments
  code/modules/augment/active/polytool.dm
  code/modules/augment/active/tool/engineering.dm
  code/modules/augment/active/tool/surgical.dm
  icons/obj/augment_tools.dmi
Labels: Спрайты

#718 Feat: place the chemical cooler on Petrov
  maps/sierra/sierra-1.dmm
Labels: Маппинг

#726 Mech fixes and equips overlay feature, mech icons(Scattergun and Lasercanon) changes.
  code/modules/mechs/components/body.dm
  code/modules/mechs/mech_icon.dm
  code/modules/mechs/mech_interaction.dm
  code/modules/mechs/mech_movement.dm
  code/modules/mechs/premade/powerloader.dm
  code/modules/mob/living/living.dm
  icons/mecha/mech_equipment.dmi
  icons/mecha/mech_weapon_overlays.dmi
  icons/mecha/mech_weapon_overlays_off.dmi
  infinity/code/modules/mechs/guns.dm
Labels: Спрайты

#724 Datajack хакеров
  baystation12.dme
  infinity/code/game/objects/items/devices/datajack.dm
  infinity/icons/obj/items.dmi
Labels: Спрайты
